export const background_variant_1 = '#161622'; // dark_blue/slate
export const background_variant_1_light = '#1d1d2b'; // dark_blue/slate
export const background_variant_2 = '#FFA001'; // yellowish/orange
export const background_variant_3 = 'rgba(205, 205, 224, 0.08)'; // transparent(showing dark_blue/slate background) - for form inputs
export const background_variant_4 = '#CDCDE0'; // white-ish/greyish
export const text_variant_1 = '#CDCDE0'; // white-ish/greyish
export const text_variant_2 = '#161622'; // dark_blue/slate
export const text_variant_3 = '#FFA001'; // yellowish/orange
export const border_variant_1 = '#CDCDE0'; // white-ish/greyish
export const border_variant_2 = '#161622'; // dark_blue/slate
export const border_variant_3 = '#FFA001'; // yellowish/orange
